spring:
  application:
    name: disbursement-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payrolladvance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: disbursement-service-group
      auto-offset-reset: earliest

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.payrolladvance: INFO
    org.springframework.web: INFO
    org.hibernate: INFO